// <auto-generated />
using CodeFirsTEFapp.Infrastructure.Appdbcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeFirsTEFapp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20230912123015_Initdb")]
    partial class Initdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeFirsTEFapp.Domain.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Subject");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("CodeFirsTEFapp.Domain.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Salary")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_Teacher");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("CodeFirsTEFapp.Domain.Models.TeacherSubject", b =>
                {
                    b.Property<int>("SubjectID")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherID")
                        .HasColumnType("integer");

                    b.HasKey("SubjectID", "TeacherID")
                        .HasName("PK_TeacherSubject");

                    b.HasIndex("TeacherID");

                    b.ToTable("TeachersSubject");
                });

            modelBuilder.Entity("CodeFirsTEFapp.Domain.Models.TeacherSubject", b =>
                {
                    b.HasOne("CodeFirsTEFapp.Domain.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TeacherSubject_Subject");

                    b.HasOne("CodeFirsTEFapp.Domain.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TeacherSubject_Teacher");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CodeFirsTEFapp.Domain.Models.Subject", b =>
                {
                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("CodeFirsTEFapp.Domain.Models.Teacher", b =>
                {
                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
